name: Release Unity Packages

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package"
        required: true
        type: choice
        options:
          - Jenny
          - Jenny.Generator
          - Jenny.Generator.Unity.Editor
          - Jenny.Plugins
          - Jenny.Plugins.Unity

concurrency: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: "Install dependencies"
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: "Build"
        run: ./build.bash ${{ inputs.package }}

      - name: "Update meta files"
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildMethod: UnityEditor.SyncVS.SyncSolution
          allowDirtyBuild: true

      - name: Commit changes
        run: |
          project="${{ inputs.package }}"
          package="com.sschmid.${project,,}"
          csproj="Jenny/src/${project}/${project}.csproj"
          version="$(xmllint --xpath 'string(/Project/PropertyGroup/Version)' "${csproj}")"

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Release ${package} ${version}"
          git push

          tag="${package}/${version}"
          git tag "${tag}"
          git push origin "${tag}"
